general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

# 3 menit : Redupin layar
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10%-
    on-resume = brightnessctl -r
}

# 30 menit : Kalo aman, baru LOCK
listener {
    timeout = 1800
    on-timeout = ~/.config/hypr/scripts/idle-check.sh "hyprlock"
}

# 10 menit : Kalo aman, baru MATIIN LAYAR (DPMS OFF)
listener    timeout = 1900
    on-timeout = ~/.config/hypr/scripts/idle-check.sh "hyprctl dispatch dpms off"
    on-resume = hyprctl dispatch dpms on
}

# 15 menit : Kalo bener-bener aman gak ada aktivitas, baru SUSPEND!
listener {
    timeout = 2000
    on-timeout = ~/.config/hypr/scripts/idle-check.sh "systemctl suspend"
}
