general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

# 3 menit → redup
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10%-
    on-resume = brightnessctl -r
}

# 5 menit → lock
listener {
    timeout = 300
    on-timeout = hyprlock
}

# 10 menit → layar mati
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 15 menit → sleep
listener {
    timeout = 900
    on-timeout = systemctl suspend
}