general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 3 Menit (180 detik) : Redupin layar pas IDLE normal
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 20%-
    on-resume = brightnessctl -r
}

# 30 Menit (1800 detik) : Matiin layar pas IDLE normal
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}