# https://wiki.hypr.land/Configuring/Variables/


# ############ LOOK AND FEEL #############

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    # gaps
    gaps_in = 2
    gaps_out = 4

    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types info colors
    # colors
    col.active_border = rgba(8aadf4ff)
    col.inactive_border = rgba(565a7aff)

    # resizing windows by clicking and dragging
    resize_on_border = false

    # https://wiki.hypr.land/Configuring/Tearing/
    allow_tearing = true

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout
dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = false
}

cursor {
    zoom_factor = 1
    zoom_rigid = false
    zoom_disable_aa = true
    hotspot_padding = 1
}

binds {
    scroll_event_delay = 1
    hide_special_on_workspace_change = true
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    # color if walpaper is not set
    background_color = rgba(1D1011FF)

    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = 1
    vrr = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    enable_swallow = false
    on_focus_under_fullscreen = 2
    allow_session_lock_restore = true
    session_lock_xray = true
    initial_workspace_tracking = false
    focus_on_activate = true
}
