#!/usr/bin/env bash

MODULE_CONFIG_DIR="${MODULE_DIR}/config"

MODULE_PACKAGES=(
  gtkmm3 
  jsoncpp
  libsigc++ 
  fmt 
  wayland 
  chrono-date 
  spdlog 
  gtk3 
  gobject-introspection 
  libgirepository 
  libpulse 
  libnl 
  libappindicator-gtk3 
  libdbusmenu-gtk3 
  libmpdclient 
  sndio 
  libevdev 
  libxkbcommon 
  upower 
  meson 
  cmake 
  scdoc 
  wayland-protocols 
  glib2-devel

  # font
  ttf-jetbrains-mono-nerd
  
)

MODULE_AUR_PACKAGES=(
  waybar-git
)
MODULE_SYSTEM_SERVICES=()
MODULE_USER_SERVICES=()
