# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:


# ############ AUTOSTART #############
# panel
exec-once = waybar

# Wallpaper
exec-once = awww-daemon
#exec-once = awww img ~/Pictures/Wallpapers/wuwa.png
exec-once = ~/.config/hypr/scripts/wallpaper.py daemon --interval 3600 --with-wal

# notify
exec-once = mako

# hypridle
exec-once = hypridle

# core components (polkit agent, idle daemon)
exec-once = systemctl --user start hyprpolkitagent.service

# gnome keyring
exec-once = gnome-keyring-daemon --start --components=secrets

# Clipboard: history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
