# ############ INPUT #############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    follow_mouse = 1
    off_window_axis_events = 2
    sensitivity = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        clickfinger_behavior = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
