#!/usr/bin/env bash

MODULE_CONFIG_DIR="${MODULE_DIR}/config"

MODULE_PACKAGES=(
    hyprland
    kitty
    hyprpolkitagent
    hypridle
    hyprlock
    xdg-user-dirs
    xdg-desktop-portal
    xdg-desktop-portal-hyprland

    # Brighnest
    brightnessctl

    # keyring
    gnome-keyring

    # font
    noto-fonts
    noto-fonts-emoji
    noto-fonts-cjk

    # file manager
    thunar

    # walpaper
    swww
    imagemagick

    # clipboard
    cliphist
    wl-clipboard

    # screenshot
    grim 
    slurp

)

MODULE_AUR_PACKAGES=(
    python-pywal16
)

MODULE_SYSTEM_SERVICES=()

MODULE_USER_SERVICES=(
    hyprpolkitagent.service
)
